source 'https://rubygems.org'

gem 'sinatra', github: 'sinatra/sinatra'
gem 'sinatra-contrib'
gem 'rake'
gem 'mongo_mapper'
gem 'bson_ext'
gem 'haml'
gem 'bcrypt'
gem 'rspec'
gem 'rack-test'
gem 'open4'
gem 'sidekiq'
gem 'memcached'
